declare namespace NodeJS {
  interface ProcessEnv {
    DATABASE_URL: string;
    DATABASE_AUTH_TOKEN?: string;
    NEXT_PUBLIC_CLERK_PUBLISHABLE_KEY: string;
    CLERK_SECRET_KEY: string;
    NEXT_PUBLIC_CLERK_SIGN_IN_URL: string;
    NEXT_PUBLIC_CLERK_SIGN_UP_URL: string;
    NEXT_PUBLIC_CLERK_AFTER_SIGN_IN_URL: string;
    NEXT_PUBLIC_CLERK_AFTER_SIGN_UP_URL: string;
    GOOGLE_CLOUD_PROJECT_ID: string;
    GOOGLE_CLOUD_CLIENT_EMAIL: string;
    GOOGLE_CLOUD_PRIVATE_KEY: string;
    GOOGLE_CLOUD_STORAGE_BUCKET: string;
  }
} 